# Generated by Django 6.0 on 2026-01-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AMC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        help_text="AMC Code from BSE/RTA", max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "AMC",
                "verbose_name_plural": "AMCs",
            },
        ),
        migrations.CreateModel(
            name="SchemeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Scheme Category",
                "verbose_name_plural": "Scheme Categories",
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("isin", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "scheme_code",
                    models.CharField(help_text="BSE Scheme Code", max_length=50),
                ),
                (
                    "rta_scheme_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "scheme_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Open Ended",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "scheme_plan",
                    models.CharField(
                        blank=True,
                        help_text="e.g. NORMAL, DIRECT",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("purchase_allowed", models.BooleanField(default=True)),
                (
                    "min_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "max_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "purchase_amount_multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=15),
                ),
                ("redemption_allowed", models.BooleanField(default=True)),
                (
                    "min_redemption_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "min_redemption_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_sip_allowed", models.BooleanField(default=False)),
                ("is_stp_allowed", models.BooleanField(default=False)),
                ("is_swp_allowed", models.BooleanField(default=False)),
                ("is_switch_allowed", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reopening_date", models.DateField(blank=True, null=True)),
                (
                    "face_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="products.amc",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.schemecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NAVHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nav_date", models.DateField()),
                (
                    "net_asset_value",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "repurchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_history",
                        to="products.scheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-nav_date"],
                "get_latest_by": "nav_date",
                "unique_together": {("scheme", "nav_date")},
            },
        ),
    ]
