# Generated by Django 6.0 on 2026-01-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="isin",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="scheme_code",
            field=models.CharField(
                help_text="BSE Scheme Code", max_length=50, unique=True
            ),
        ),
    ]
