# Generated by Django 6.0.1 on 2026-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_scheme_isin_alter_scheme_scheme_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="additional_purchase_amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="scheme",
            name="amc_active_flag",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="amc_ind",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="amc_scheme_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="channel_partner_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="dividend_reinvestment_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheme",
            name="exit_load",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="exit_load_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheme",
            name="lock_in_period",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="lock_in_period_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheme",
            name="max_redemption_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="scheme",
            name="max_redemption_qty",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="scheme",
            name="purchase_cutoff_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="purchase_transaction_mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="redemption_amount_multiple",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="scheme",
            name="redemption_cutoff_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="redemption_qty_multiplier",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="scheme",
            name="redemption_transaction_mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="rta_agent_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="unique_no",
            field=models.BigIntegerField(
                blank=True, help_text="BSE Unique No", null=True, unique=True
            ),
        ),
    ]
