# Generated by Django 6.0.1 on 2026-02-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_scheme_additional_purchase_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="amfi_code",
            field=models.CharField(
                blank=True,
                help_text="AMFI Scheme Code",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
