# Generated by Django 6.0.1 on 2026-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_scheme_amfi_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="amfi_code",
            field=models.CharField(
                blank=True, help_text="AMFI Scheme Code", max_length=50, null=True
            ),
        ),
    ]
