# Generated by Django 6.0.1 on 2026-02-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_scheme_amfi_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="amc",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
