# Generated by Django 6.0.1 on 2026-02-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_amc_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="scheme",
            name="about_fund",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="aum",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Assets Under Management in Cr",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheme",
            name="benchmark_index",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="expense_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Expense Ratio %",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheme",
            name="riskometer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low", "Low"),
                    ("Low to Moderate", "Low to Moderate"),
                    ("Moderate", "Moderate"),
                    ("Moderately High", "Moderately High"),
                    ("High", "High"),
                    ("Very High", "Very High"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SchemeAssetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        help_text="Equity, Debt, Cash, etc.", max_length=100
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_allocations",
                        to="products.scheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchemeHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Holding percentage (e.g. 5.50)",
                        max_digits=5,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_holdings",
                        to="products.scheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-percentage"],
            },
        ),
        migrations.CreateModel(
            name="SchemeManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="products.fundmanager",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managers",
                        to="products.scheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchemeSectorAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector_name", models.CharField(max_length=100)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_allocations",
                        to="products.scheme",
                    ),
                ),
            ],
        ),
    ]
