# Generated by Django 6.0.1 on 2026-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_fundmanager_scheme_about_fund_scheme_aum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Set to False to disable this scheme for new investments.",
            ),
        ),
    ]
