# Generated by Django 6.0.1 on 2026-04-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_scheme_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="family_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="mfdata.in Family ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schemeholding",
            name="market_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Market Value",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schemeholding",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Quantity",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="schemeassetallocation",
            name="percentage",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="schemeholding",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Holding percentage (e.g. 5.50)",
                max_digits=8,
            ),
        ),
        migrations.CreateModel(
            name="SchemeRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField(blank=True, null=True)),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pb_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ps_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "jensens_alpha",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "treynor_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "information_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "std_deviation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "beta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sortino_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "r_squared",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "scheme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratios",
                        to="products.scheme",
                    ),
                ),
            ],
        ),
    ]
