# Generated by Django 6.0.1 on 2026-04-17 17:35

import django.contrib.postgres.indexes
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_scheme_family_id_schemeholding_market_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BSESchemeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bse_code", models.CharField(max_length=20, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("LUMPSUM", "LUMPSUM"),
                            ("SIP", "SIP"),
                            ("STP", "STP"),
                            ("SWP", "SWP"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalBSESchemeMapping",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("bse_code", models.CharField(db_index=True, max_length=20)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("LUMPSUM", "LUMPSUM"),
                            ("SIP", "SIP"),
                            ("STP", "STP"),
                            ("SWP", "SWP"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bse scheme mapping",
                "verbose_name_plural": "historical bse scheme mappings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRTASchemeMapping",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("rta_code", models.CharField(db_index=True, max_length=50)),
                ("rta_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical rta scheme mapping",
                "verbose_name_plural": "historical rta scheme mappings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalScheme",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("isin", models.CharField(db_index=True, max_length=20)),
                (
                    "scheme_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="BSE Scheme Code (legacy)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "unique_no",
                    models.BigIntegerField(
                        blank=True, db_index=True, help_text="BSE Unique No", null=True
                    ),
                ),
                (
                    "rta_scheme_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "amc_scheme_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "amfi_code",
                    models.CharField(
                        blank=True,
                        help_text="AMFI Scheme Code",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "scheme_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Open Ended",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        blank=True,
                        choices=[("DIRECT", "Direct"), ("REGULAR", "Regular")],
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        blank=True,
                        choices=[("GROWTH", "Growth"), ("IDCW", "IDCW")],
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "scheme_plan",
                    models.CharField(
                        blank=True,
                        help_text="Legacy e.g. NORMAL, DIRECT",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("purchase_allowed", models.BooleanField(default=True)),
                (
                    "purchase_transaction_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "additional_purchase_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "max_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "purchase_amount_multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=15),
                ),
                ("purchase_cutoff_time", models.TimeField(blank=True, null=True)),
                ("redemption_allowed", models.BooleanField(default=True)),
                (
                    "redemption_transaction_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "min_redemption_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "redemption_qty_multiplier",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "max_redemption_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "min_redemption_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "max_redemption_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "redemption_amount_multiple",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("redemption_cutoff_time", models.TimeField(blank=True, null=True)),
                ("is_sip_allowed", models.BooleanField(default=False)),
                ("is_stp_allowed", models.BooleanField(default=False)),
                ("is_swp_allowed", models.BooleanField(default=False)),
                ("is_switch_allowed", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reopening_date", models.DateField(blank=True, null=True)),
                (
                    "aum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Assets Under Management in Cr",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "expense_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expense Ratio %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "benchmark_index",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "riskometer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Low to Moderate", "Low to Moderate"),
                            ("Moderate", "Moderate"),
                            ("Moderately High", "Moderately High"),
                            ("High", "High"),
                            ("Very High", "Very High"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("about_fund", models.TextField(blank=True, null=True)),
                (
                    "face_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "rta_agent_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("amc_active_flag", models.BooleanField(default=True)),
                ("dividend_reinvestment_flag", models.BooleanField(default=False)),
                ("amc_ind", models.CharField(blank=True, max_length=50, null=True)),
                ("exit_load_flag", models.BooleanField(default=False)),
                ("exit_load", models.TextField(blank=True, null=True)),
                ("lock_in_period_flag", models.BooleanField(default=False)),
                (
                    "lock_in_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "channel_partner_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to disable this scheme for new investments.",
                    ),
                ),
                (
                    "family_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="mfdata.in Family ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical scheme",
                "verbose_name_plural": "historical schemes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RTASchemeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rta_code", models.CharField(max_length=50, unique=True)),
                ("rta_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnmatchedSchemeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("AMFI", "AMFI"), ("BSE", "BSE"), ("RTA", "RTA")],
                        max_length=50,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(help_text="The raw row data that failed to match"),
                ),
                ("reason", models.TextField(help_text="Why it failed to match")),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="scheme",
            name="normalized_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="scheme",
            name="option",
            field=models.CharField(
                blank=True,
                choices=[("GROWTH", "Growth"), ("IDCW", "IDCW")],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheme",
            name="plan_type",
            field=models.CharField(
                blank=True,
                choices=[("DIRECT", "Direct"), ("REGULAR", "Regular")],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navhistory",
            name="nav_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="amc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schemes",
                to="products.amc",
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="scheme_code",
            field=models.CharField(
                blank=True,
                help_text="BSE Scheme Code (legacy)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="scheme_plan",
            field=models.CharField(
                blank=True,
                help_text="Legacy e.g. NORMAL, DIRECT",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="navhistory",
            index=models.Index(
                fields=["scheme", "-nav_date"], name="navhist_scheme_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navhistory",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["nav_date"], name="navhist_date_brin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheme",
            index=models.Index(
                fields=["isin", "plan_type", "option"],
                name="products_sc_isin_089b7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheme",
            index=models.Index(
                fields=["amfi_code"], name="products_sc_amfi_co_10efad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheme",
            index=models.Index(
                fields=["normalized_name"], name="products_sc_normali_ecbe7b_idx"
            ),
        ),
        migrations.AddField(
            model_name="bseschememapping",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bse_mappings",
                to="products.scheme",
            ),
        ),
        migrations.AddField(
            model_name="historicalbseschememapping",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbseschememapping",
            name="scheme",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.scheme",
            ),
        ),
        migrations.AddField(
            model_name="historicalrtaschememapping",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalrtaschememapping",
            name="scheme",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.scheme",
            ),
        ),
        migrations.AddField(
            model_name="historicalscheme",
            name="amc",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.amc",
            ),
        ),
        migrations.AddField(
            model_name="historicalscheme",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.schemecategory",
            ),
        ),
        migrations.AddField(
            model_name="historicalscheme",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rtaschememapping",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rta_mappings",
                to="products.scheme",
            ),
        ),
        migrations.AddIndex(
            model_name="bseschememapping",
            index=models.Index(
                fields=["scheme", "transaction_type"],
                name="products_bs_scheme__e4f04f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bseschememapping",
            index=models.Index(
                fields=["bse_code"], name="products_bs_bse_cod_57eade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rtaschememapping",
            index=models.Index(
                fields=["rta_code"], name="products_rt_rta_cod_55d42b_idx"
            ),
        ),
    ]
