# Generated by Django 6.0.1 on 2026-01-09 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_scheme_isin_alter_scheme_scheme_code"),
        ("users", "0003_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio_number", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folios",
                        to="products.amc",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folios",
                        to="users.investorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folio",
                "verbose_name_plural": "Folios",
                "unique_together": {("investor", "amc", "folio_number")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("P", "Purchase"),
                            ("R", "Redemption"),
                            ("S", "Switch"),
                            ("SIP", "SIP Registration"),
                        ],
                        default="P",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Investment Amount", max_digits=15
                    ),
                ),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Units for Redemption/Switch",
                        max_digits=15,
                    ),
                ),
                (
                    "allotted_units",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "unique_ref_no",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "bse_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bse_remarks", models.TextField(blank=True, null=True)),
                (
                    "euin",
                    models.CharField(
                        blank=True,
                        help_text="EUIN used for this transaction",
                        max_length=50,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Net Banking"),
                            ("UPI", "UPI"),
                            ("NEFT", "NEFT/RTGS"),
                            ("MANDATE", "Mandate"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                (
                    "payment_ref_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_link", models.URLField(blank=True, null=True)),
                (
                    "is_new_folio",
                    models.BooleanField(
                        default=False, help_text="If True, request new folio creation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT_TO_BSE", "Sent to BSE"),
                            ("AWAITING_PAYMENT", "Awaiting Payment"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ALLOTTED", "Allotted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="users.distributorprofile",
                    ),
                ),
                (
                    "folio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked Folio if existing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="investments.folio",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="users.investorprofile",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="products.scheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
