# Generated by Django 6.0.1 on 2026-01-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
        ("users", "0003_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("P", "Lumpsum Purchase"),
                    ("R", "Redemption"),
                    ("S", "Switch"),
                    ("SIP", "SIP Registration"),
                ],
                default="P",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mandate_id",
                    models.CharField(
                        help_text="UMRN or Mandate ID from BSE",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "amount_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum amount allowed per transaction",
                        max_digits=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mandates",
                        to="users.bankaccount",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="users.investorprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="mandate",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for SIP",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="investments.mandate",
            ),
        ),
    ]
