# Generated by Django 6.0.1 on 2026-01-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_alter_order_transaction_type_mandate_order_mandate"),
        ("products", "0002_alter_scheme_isin_alter_scheme_scheme_code"),
        ("users", "0003_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("WEEKLY", "Weekly"),
                            ("QUARTERLY", "Quarterly"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "installments",
                    models.IntegerField(help_text="Number of installments"),
                ),
                (
                    "bse_sip_id",
                    models.CharField(
                        blank=True,
                        help_text="BSE SIP Registration ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bse_reg_no",
                    models.CharField(
                        blank=True,
                        help_text="BSE XSIP Registration Number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sips",
                        to="investments.folio",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sips",
                        to="users.investorprofile",
                    ),
                ),
                (
                    "mandate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sips",
                        to="investments.mandate",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sips",
                        to="products.scheme",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="sip_reg",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked SIP Registration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registration_orders",
                to="investments.sip",
            ),
        ),
    ]
