# Generated by Django 6.0.1 on 2026-01-18 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_sip_order_sip_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bse_order_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='unique_ref_no',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
    ]
