# Generated by Django 6.0.1 on 2026-01-18 20:11

import apps.investments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0004_alter_order_bse_order_id_alter_order_unique_ref_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="unique_ref_no",
            field=models.CharField(
                default=apps.investments.models.generate_order_unique_ref_no,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
