# Generated by Django 6.0.1 on 2026-01-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0005_alter_order_unique_ref_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandate",
            name="mandate_type",
            field=models.CharField(
                choices=[
                    ("X", "Physical (XSIP)"),
                    ("I", "E-Mandate (ISIP)"),
                    ("N", "E-Mandate (Net Banking)"),
                ],
                default="I",
                help_text="Type of Mandate",
                max_length=1,
            ),
        ),
    ]
