# Generated by Django 6.0.1 on 2026-01-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0006_mandate_mandate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sip",
            name="euin",
            field=models.CharField(
                blank=True, help_text="EUIN used for this transaction", max_length=50
            ),
        ),
        # STEP 1: Add field as nullable (null=True) and NOT unique yet
        migrations.AddField(
            model_name="sip",
            name="unique_ref_no",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="unique_ref_no",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
