# Generated by Django 6.0.1 on 2026-01-22 04:57

from django.db import migrations
from apps.investments.utils import generate_distributor_based_ref

def populate_sip_ref_and_euin(apps, schema_editor):
    SIP = apps.get_model('investments', 'SIP')
    SystemConfiguration = apps.get_model('administration', 'SystemConfiguration')
    for sip in SIP.objects.all():
        # Generate Ref No
        dist_id = 0
        if sip.investor and sip.investor.distributor:
            dist_id = sip.investor.distributor.id

        # Ensure unique by regenerating if needed (simple check)
        sip.unique_ref_no = generate_distributor_based_ref(dist_id)

        # Populate EUIN
        if sip.investor.distributor and sip.investor.distributor.euin:
            sip.euin = sip.investor.distributor.euin
        else:
            # We use .first() because this is a migration and we might not have get_solo
            config = SystemConfiguration.objects.first()
            if config and config.default_euin:
                sip.euin = config.default_euin
            else:
                sip.euin = ""

        sip.save()

class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0007_sip_euin_sip_unique_ref_no_alter_order_unique_ref_no"),
    ]

    operations = [
        migrations.RunPython(populate_sip_ref_and_euin),
    ]
