# Generated by Django 6.0.1 on 2026-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0009_enforce_sip_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="all_redeem",
            field=models.BooleanField(
                default=False, help_text="If True, redeem all units"
            ),
        ),
    ]
