# Generated by Django 6.0.1 on 2026-01-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0010_order_all_redeem"),
        ("products", "0002_alter_scheme_isin_alter_scheme_scheme_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="target_scheme",
            field=models.ForeignKey(
                blank=True,
                help_text="Target Scheme for Switch Orders",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="switch_orders",
                to="products.scheme",
            ),
        ),
    ]
