# Generated by Django 6.0.1 on 2026-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_order_target_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sip',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=20),
        ),
    ]
