# Generated by Django 6.0.1 on 2026-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0012_alter_sip_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="sip",
            name="last_alert_sent_date",
            field=models.DateField(
                blank=True,
                help_text="Last date an SMS alert was sent for an upcoming installment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sip",
            name="next_installment_date",
            field=models.DateField(
                blank=True,
                help_text="Calculated date for the next SIP installment",
                null=True,
            ),
        ),
    ]
