# Generated by Django 6.0.1 on 2026-03-21 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0013_sip_last_alert_sent_date_sip_next_installment_date"),
        ("reconciliation", "0012_orderreconciliation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sip",
            name="installment_day",
            field=models.IntegerField(
                blank=True,
                help_text="Day of the month (e.g., 5 for 5th of every month)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sip",
            name="installments",
            field=models.IntegerField(
                blank=True, help_text="Total number of installments", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sip",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("PENDING", "Pending"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SIPInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        help_text="BSE Order ID or Reg No",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("TRIGGERED", "Triggered"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sip_master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sip_installments",
                        to="investments.sip",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sip_installments",
                        to="reconciliation.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
                "indexes": [
                    models.Index(
                        fields=["sip_master", "due_date"],
                        name="investments_sip_mas_89bcd5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="investments_status_1a1852_idx"
                    ),
                    models.Index(
                        fields=["order_id"], name="investments_order_i_b125c9_idx"
                    ),
                    models.Index(
                        fields=["transaction"], name="investments_transac_d2c154_idx"
                    ),
                ],
            },
        ),
    ]
