# Generated by Django 6.0.1 on 2026-03-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0014_sip_installment_day_alter_sip_installments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sip",
            name="failure_reason",
            field=models.TextField(
                blank=True, help_text="Reason for failure or cancellation", null=True
            ),
        ),
        migrations.AddField(
            model_name="sipinstallment",
            name="remarks",
            field=models.CharField(
                blank=True,
                help_text="RTA Remarks or Description",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sipinstallment",
            name="reversal_code",
            field=models.CharField(
                blank=True, help_text="RTA Reversal Code", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="sipinstallment",
            name="rta_txn_number",
            field=models.CharField(
                blank=True,
                help_text="Original RTA Transaction No",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sipinstallment",
            name="siptrxnno",
            field=models.CharField(
                blank=True,
                help_text="RTA SIP Transaction Number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sipinstallment",
            name="status_desc",
            field=models.CharField(
                blank=True,
                help_text="RTA Status Description",
                max_length=100,
                null=True,
            ),
        ),
    ]
