# Generated by Django 6.0.1 on 2026-03-21 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0015_sip_failure_reason_sipinstallment_remarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sip",
            name="mandate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sips",
                to="investments.mandate",
            ),
        ),
    ]
