import sys

migration_code = """# Generated by Django 6.0.1 on 2026-03-19 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_scheme_is_active"),
        ("reconciliation", "0011_failedrtarecord"),
        ("users", "0028_user_force_password_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(db_index=True, max_length=100)),
                (
                    "folio_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("PARTIAL", "Partial Match"),
                            ("MISMATCH", "Mismatch"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("match_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameField(
            model_name="failedrtarecord",
            old_name="original_txn_number",
            new_name="txn_number",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="txn_number",
            field=models.CharField(
                default="",
                help_text="SHA256 fingerprint for deduplication",
                max_length=255,
            ),
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="txn_number",
            new_name="fingerprint",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="original_txn_number",
            new_name="txn_number",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fingerprint",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="SHA256 fingerprint for deduplication",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="txn_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Original RTA Transaction No",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="match_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="origin",
            field=models.CharField(
                choices=[
                    ("BSE", "BSE Star MF"),
                    ("AMC", "AMC Direct"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                help_text="Identified source of the transaction",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["scheme", "date"], name="reconciliat_scheme__1bb161_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["fingerprint"], name="reconciliat_fingerp_a60d01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["amount"], name="reconciliat_amount_a421d3_idx"),
        ),
        migrations.AddField(
            model_name="orderreconciliation",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reconciliations",
                to="users.investorprofile",
            ),
        ),
        migrations.AddField(
            model_name="orderreconciliation",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reconciliations",
                to="products.scheme",
            ),
        ),
        migrations.AddField(
            model_name="orderreconciliation",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciliations",
                to="reconciliation.transaction",
            ),
        ),
    ]
"""

with open("apps/reconciliation/migrations/0012_orderreconciliation_and_more.py", "w") as f:
    f.write(migration_code)
