# Generated by Django 6.0.1 on 2026-01-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_scheme_isin_alter_scheme_scheme_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amc",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to apply to all AMCs for this category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="products.amc",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="products.schemecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Rule",
                "verbose_name_plural": "Commission Rules",
                "unique_together": {("category", "amc")},
            },
        ),
        migrations.CreateModel(
            name="CommissionTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_aum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum AUM (>=)",
                        max_digits=15,
                    ),
                ),
                (
                    "max_aum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum AUM (<). Leave blank for infinity.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission Rate in % (e.g. 0.80)",
                        max_digits=5,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="payouts.commissionrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Tier",
                "verbose_name_plural": "Commission Tiers",
                "ordering": ["min_aum"],
            },
        ),
    ]
