# Generated by Django 6.0.1 on 2026-01-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0016_branch_investorprofile_rm_investorprofile_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "min_aum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum AUM in Rupees",
                        max_digits=15,
                    ),
                ),
                (
                    "max_aum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum AUM in Rupees (Leave blank for infinity)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "share_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of brokerage given to distributor (e.g., 60.00)",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Distributor Categories",
                "ordering": ["min_aum"],
            },
        ),
        migrations.CreateModel(
            name="BrokerageImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "cams_file",
                    models.FileField(
                        blank=True, null=True, upload_to="brokerage/cams/%Y/%m/"
                    ),
                ),
                (
                    "karvy_file",
                    models.FileField(
                        blank=True, null=True, upload_to="brokerage/karvy/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_log", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="BrokerageTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("CAMS", "CAMS"), ("KARVY", "Karvy")], max_length=10
                    ),
                ),
                ("transaction_date", models.DateField(blank=True, null=True)),
                ("investor_name", models.CharField(blank=True, max_length=255)),
                ("folio_number", models.CharField(blank=True, max_length=50)),
                ("scheme_name", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "brokerage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_mapped", models.BooleanField(default=False)),
                ("mapping_remark", models.CharField(blank=True, max_length=255)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brokerage_transactions",
                        to="users.distributorprofile",
                    ),
                ),
                (
                    "import_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payouts.brokerageimport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_aum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total AUM of Distributor at time of calculation",
                        max_digits=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "share_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gross_brokerage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total brokerage received from RTA",
                        max_digits=15,
                    ),
                ),
                (
                    "payable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount payable to Distributor",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CALCULATED", "Calculated"), ("PAID", "Paid")],
                        default="CALCULATED",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brokerage_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="payouts.brokerageimport",
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="users.distributorprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-brokerage_import__year",
                    "-brokerage_import__month",
                    "distributor",
                ],
            },
        ),
    ]
