# Generated by Django 6.0.1 on 2026-01-11 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0001_initial"),
        ("reconciliation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_date",
                    models.DateField(
                        help_text="The month/year this payout represents (usually 1st of month)"
                    ),
                ),
                (
                    "total_aum",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PAID", "Paid")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "distributor",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "DISTRIBUTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_date", "distributor"],
                "unique_together": {("distributor", "period_date")},
            },
        ),
        migrations.CreateModel(
            name="PayoutDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investor_name", models.CharField(max_length=255)),
                ("scheme_name", models.CharField(max_length=255)),
                ("folio_number", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(max_length=100)),
                ("amc_name", models.CharField(max_length=255)),
                (
                    "aum",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="AUM used for calculation",
                        max_digits=20,
                    ),
                ),
                (
                    "applied_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate % applied", max_digits=5
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "holding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payout_details",
                        to="reconciliation.holding",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="payouts.payout",
                    ),
                ),
            ],
        ),
    ]
