# Generated by Django 6.0.1 on 2026-02-24 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0001_initial"),
        ("products", "0007_fundmanager_scheme_about_fund_scheme_aum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeragetransaction",
            name="scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brokerage_transactions",
                to="products.scheme",
            ),
        ),
    ]
