# Generated by Django 6.0.1 on 2026-02-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0002_brokeragetransaction_scheme"),
        ("users", "0027_rmprofile_pan"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolioDistributorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folio_mappings",
                        to="users.distributorprofile",
                    ),
                ),
            ],
        ),
    ]
