
STATE_CHOICES = [
    ('ANDAMAN & NICOBAR', 'Andaman & Nicobar'),
    ('ANDHRA PRADESH', 'Andhra Pradesh'),
    ('ARUNACHAL PRADESH', 'Arunachal Pradesh'),
    ('ASSAM', 'Assam'),
    ('BIHAR', 'Bihar'),
    ('CHANDIGARH', 'Chandigarh'),
    ('CHHATTISGARH', 'Chhattisgarh'),
    ('DADRA AND NAGAR HAVELI', 'Dadra and Nagar Haveli'),
    ('DAMAN AND DIU', 'Daman and Diu'),
    ('DELHI', 'Delhi'),
    ('GOA', 'Goa'),
    ('GUJARAT', 'Gujarat'),
    ('HARYANA', 'Haryana'),
    ('HIMACHAL PRADESH', 'Himachal Pradesh'),
    ('JAMMU & KASHMIR', 'Jammu & Kashmir'),
    ('JHARKHAND', 'Jharkhand'),
    ('KARNATAKA', 'Karnataka'),
    ('KERALA', 'Kerala'),
    ('LAKSHADWEEP', 'Lakshadweep'),
    ('MADHYA PRADESH', 'Madhya Pradesh'),
    ('MAHARASHTRA', 'Maharashtra'),
    ('MANIPUR', 'Manipur'),
    ('MEGHALAYA', 'Meghalaya'),
    ('MIZORAM', 'Mizoram'),
    ('NAGALAND', 'Nagaland'),
    ('NEW DELHI', 'New Delhi'),
    ('ODISHA', 'Odisha'),
    ('PUDUCHERRY', 'Puducherry'),
    ('PUNJAB', 'Punjab'),
    ('RAJASTHAN', 'Rajasthan'),
    ('SIKKIM', 'Sikkim'),
    ('TAMIL NADU', 'Tamil Nadu'),
    ('TELANGANA', 'Telangana'),
    ('TRIPURA', 'Tripura'),
    ('UTTAR PRADESH', 'Uttar Pradesh'),
    ('UTTARAKHAND', 'Uttarakhand'),
    ('WEST BENGAL', 'West Bengal'),
]

STATE_MAPPING = {
    'ANDAMAN & NICOBAR': 'AN', 'ANDHRA PRADESH': 'AP', 'ARUNACHAL PRADESH': 'AR',
    'ASSAM': 'AS', 'BIHAR': 'BH', 'CHANDIGARH': 'CH', 'CHHATTISGARH': 'CG',
    'DADRA AND NAGAR HAVELI': 'DN', 'DAMAN AND DIU': 'DD', 'DELHI': 'DL',
    'GOA': 'GO', 'GUJARAT': 'GU', 'HARYANA': 'HA', 'HIMACHAL PRADESH': 'HP',
    'JAMMU & KASHMIR': 'JM', 'JHARKHAND': 'JK', 'KARNATAKA': 'KA', 'KERALA': 'KE',
    'LAKSHADWEEP': 'LD', 'MADHYA PRADESH': 'MP', 'MAHARASHTRA': 'MA', 'MANIPUR': 'MN',
    'MEGHALAYA': 'ME', 'MIZORAM': 'MI', 'NAGALAND': 'NA', 'NEW DELHI': 'ND',
    'ODISHA': 'OR', 'ORISSA': 'OR', 'PUDUCHERRY': 'PO', 'PONDICHERRY': 'PO',
    'PUNJAB': 'PU', 'RAJASTHAN': 'RA', 'SIKKIM': 'SI', 'TAMIL NADU': 'TN',
    'TELANGANA': 'TG', 'TRIPURA': 'TR', 'UTTAR PRADESH': 'UP', 'UTTARAKHAND': 'UC',
    'UTTARANCHAL': 'UC', 'WEST BENGAL': 'WB'
}
