"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-j3$*!3y*#6vw3*%k5a4895&589oh!2a#=o#r+y7cxm=c-ty5+v')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'widget_tweaks',
    'apps.administration',
    'apps.core',
    'apps.users',
    'apps.products',
    'apps.investments',
    'apps.payouts',
    'apps.integration',
    'apps.analytics',
    'apps.reconciliation',
    'apps.reports',
    'apps.website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'buybestfin-main/dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-in'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_THOUSAND_SEPARATOR = False

FORMAT_MODULE_PATH = [
    'apps.core.formats',
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'administration:index'
LOGOUT_REDIRECT_URL = 'users:login'

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'assets'), os.path.join(BASE_DIR, 'buybestfin-main/dist')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# BSE StarMF API Configuration
BSE_MEMBER_ID = os.environ.get('BSE_MEMBER_ID', "24637")
BSE_USER_ID = os.environ.get('BSE_USER_ID', "2463702")
BSE_PASSWORD = os.environ.get('BSE_PASSWORD', "Abc@1234")

BSE_ENV = os.environ.get('BSE_ENV', 'DEMO').upper()

# WSDL Base Directory
WSDL_DIR = os.path.join(BASE_DIR, 'docs', 'wsdl', 'prod' if BSE_ENV == 'PROD' else 'demo')

# BSE StarMF API URLs and WSDLs
if BSE_ENV == 'PROD':
    BSE_ORDER_WSDL = os.environ.get('BSE_ORDER_WSDL', f"file://{os.path.join(WSDL_DIR, 'MFOrder.wsdl')}")
    BSE_UPLOAD_WSDL = os.environ.get('BSE_UPLOAD_WSDL', f"file://{os.path.join(WSDL_DIR, 'MFUploadService.wsdl')}")
    BSE_QUERY_WSDL = os.environ.get('BSE_QUERY_WSDL', f"file://{os.path.join(WSDL_DIR, 'StarMFWebService.wsdl')}")

    BSE_UPLOAD_SERVICE_URL = os.environ.get('BSE_UPLOAD_SERVICE_URL', "https://bsestarmf.in/StarMFFileUploadService/StarMFFileUploadService.svc/Secure/UploadFile")
    BSE_COMMON_API_URL = os.environ.get('BSE_COMMON_API_URL', "https://bsestarmf.in/BSEMFWEBAPI/UCCAPI/UCCRegistrationV183")
    BSE_EMANDATE_AUTH_URL = os.environ.get('BSE_EMANDATE_AUTH_URL', "https://bsestarmf.in/Emandate/EmandateAuthURL.aspx")
    BSE_EMANDATE_API_URL = os.environ.get('BSE_EMANDATE_API_URL', "https://bsestarmf.in/StarMFWebService/StarMFWebService.svc/EMandateAuthURL")
    BSE_NOMINEE_API_URL = os.environ.get('BSE_NOMINEE_API_URL', "https://bsestarmf.in/BSEMFWEBAPI/api/NomineeFlag/Change")
else:
    # Defaults to DEMO
    BSE_ORDER_WSDL = os.environ.get('BSE_ORDER_WSDL', f"file://{os.path.join(WSDL_DIR, 'MFOrder.wsdl')}")
    BSE_UPLOAD_WSDL = os.environ.get('BSE_UPLOAD_WSDL', f"file://{os.path.join(WSDL_DIR, 'MFUploadService.wsdl')}")
    BSE_QUERY_WSDL = os.environ.get('BSE_QUERY_WSDL', f"file://{os.path.join(WSDL_DIR, 'StarMFWebService.wsdl')}")

    BSE_UPLOAD_SERVICE_URL = os.environ.get('BSE_UPLOAD_SERVICE_URL', "https://bsestarmfdemo.bseindia.com/StarMFFileUploadService/StarMFFileUploadService.svc/Secure/UploadFile")
    BSE_COMMON_API_URL = os.environ.get('BSE_COMMON_API_URL', "https://bsestarmfdemo.bseindia.com/BSEMFWEBAPI/UCCAPI/UCCRegistrationV183")
    BSE_EMANDATE_AUTH_URL = os.environ.get('BSE_EMANDATE_AUTH_URL', "https://bsestarmfdemo.bseindia.com/Emandate/EmandateAuthURL.aspx")
    BSE_EMANDATE_API_URL = os.environ.get('BSE_EMANDATE_API_URL', "https://bsestarmfdemo.bseindia.com/StarMFWebService/StarMFWebService.svc/EMandateAuthURL")
    BSE_NOMINEE_API_URL = os.environ.get('BSE_NOMINEE_API_URL', "https://bsestarmfdemo.bseindia.com/BSEMFWEBAPI/api/NomineeFlag/Change")

# CVL KRA API Configuration
CVL_USER_NAME = os.environ.get('CVL_USER_NAME', "WEBADMIN")
CVL_POS_CODE = os.environ.get('CVL_POS_CODE', "5100147231")
CVL_PASSWORD = os.environ.get('CVL_PASSWORD', "E8B0D03E2A")
# Optional override for the service URL endpoint
CVL_SERVICE_URL = os.environ.get('CVL_SERVICE_URL', "https://pancheck.www.kracvl.com/CVLPANInquiry.svc?singleWsdl")

# RTA Email Configuration
RTA_EMAIL_HOST = os.environ.get('RTA_EMAIL_HOST', 'imap.gmail.com')
RTA_EMAIL_PORT = int(os.environ.get('RTA_EMAIL_PORT', 993))
RTA_EMAIL_USER = os.environ.get('RTA_EMAIL_USER', 'info@navinchandrasecurities.com')
RTA_EMAIL_PASSWORD = os.environ.get('RTA_EMAIL_PASSWORD', 'zqdcbricbumdqyyo')

# Passwords for encrypted RTA files (comma-separated list)
# Note: RTA_FILE_PASSWORD env var should be comma separated if multiple
RTA_FILE_PASSWORD = [p.strip() for p in os.environ.get('RTA_FILE_PASSWORD', '123456,Navin@2026').split(',') if p.strip()]

# Filters for identifying relevant emails
# Note: Env vars should be comma separated
RTA_EMAIL_SENDER_FILTERS = [s.strip().lower() for s in os.environ.get('RTA_EMAIL_SENDER_FILTERS', 'donotreply@camsonline.com,distributorcare@kfintech.com').split(',') if s.strip()]
RTA_EMAIL_SUBJECT_FILTERS = [s.strip().lower() for s in os.environ.get('RTA_EMAIL_SUBJECT_FILTERS', 'Subscribed Transaction Feeds Report,WBR2. Investor Transactions for a Period').split(',') if s.strip()]

# Number of days to look back for emails
RTA_EMAIL_FETCH_DAYS = int(os.environ.get('RTA_EMAIL_FETCH_DAYS', 3))

# SMS Configuration
SMS_API_KEY = os.environ.get('SMS_API_KEY', '64c7a50d19c21')
SMS_SENDER_ID = os.environ.get('SMS_SENDER_ID', 'NSPLMF')
SMS_BASE_URL = os.environ.get('SMS_BASE_URL', 'http://sms.mobileadz.in/api/push.json')
