# Generated by Django 6.0.1 on 2026-01-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investorprofile",
            name="address",
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="address_1",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="address_2",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="address_3",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="country",
            field=models.CharField(blank=True, default="India", max_length=35),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="guardian_name",
            field=models.CharField(
                blank=True, help_text="Required if Tax Status is Minor", max_length=70
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="guardian_pan",
            field=models.CharField(
                blank=True, help_text="Required if Tax Status is Minor", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="holding_nature",
            field=models.CharField(
                choices=[
                    ("SI", "Single"),
                    ("JO", "Joint"),
                    ("AS", "Anyone or Survivor"),
                ],
                default="SI",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("01", "Business"),
                    ("02", "Service"),
                    ("03", "Professional"),
                    ("04", "Agriculturist"),
                    ("05", "Retired"),
                    ("06", "Housewife"),
                    ("07", "Student"),
                    ("08", "Others"),
                ],
                default="02",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="second_applicant_name",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="second_applicant_pan",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="state",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="tax_status",
            field=models.CharField(
                choices=[
                    ("01", "Individual"),
                    ("02", "On Behalf of Minor"),
                    ("03", "HUF"),
                    ("04", "Company"),
                    ("21", "NRI (Repatriable)"),
                    ("24", "NRI (Non-Repatriable)"),
                ],
                default="01",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="third_applicant_name",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="third_applicant_pan",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="ucc_code",
            field=models.CharField(
                blank=True,
                help_text="Unique Client Code from BSE",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ifsc_code", models.CharField(max_length=11)),
                ("account_number", models.CharField(max_length=20)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SB", "Savings"),
                            ("CB", "Current"),
                            ("NE", "NRE"),
                            ("NO", "NRO"),
                        ],
                        default="SB",
                        max_length=2,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("branch_name", models.CharField(blank=True, max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="users.investorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nominee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("relationship", models.CharField(max_length=50)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of allocation",
                        max_digits=5,
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True, help_text="If nominee is a minor", max_length=100
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominees",
                        to="users.investorprofile",
                    ),
                ),
            ],
        ),
    ]
