# Generated by Django 6.0.1 on 2026-01-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_investorprofile_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PAN", "PAN Card"),
                            ("AADHAAR", "Aadhaar Card"),
                            ("CHEQUE", "Cancelled Cheque"),
                            ("OTHERS", "Others"),
                        ],
                        default="OTHERS",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.investorprofile",
                    ),
                ),
            ],
        ),
    ]
