# Generated by Django 6.0.1 on 2026-01-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominee",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Required if nominee is a minor", null=True
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="guardian_pan",
            field=models.CharField(
                blank=True, help_text="If nominee is a minor", max_length=10
            ),
        ),
    ]
