# Generated by Django 6.0.1 on 2026-01-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_nominee_date_of_birth_nominee_guardian_pan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nominee",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("Spouse", "Spouse"),
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Son", "Son"),
                    ("Daughter", "Daughter"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=50,
            ),
        ),
    ]
