# Generated by Django 6.0.1 on 2026-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_nominee_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="client_id",
            field=models.CharField(
                blank=True, help_text="Beneficiary ID / Client ID", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="client_type",
            field=models.CharField(
                choices=[("P", "Physical"), ("D", "Demat")], default="P", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="depository",
            field=models.CharField(
                blank=True, choices=[("C", "CDSL"), ("N", "NSDL")], max_length=1
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="dp_id",
            field=models.CharField(
                blank=True, help_text="Depository Participant ID", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="pan",
            field=models.CharField(
                blank=True, help_text="Nominee PAN (Optional)", max_length=10
            ),
        ),
    ]
