# Generated by Django 6.0.1 on 2026-01-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_investorprofile_foreign_address_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_address_1",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_address_2",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_address_3",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_city",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_country",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_off_fax",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_off_phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_pincode",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_res_fax",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_resi_phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="foreign_state",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="lei_no",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="mapin_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="address_1",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="address_2",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="address_3",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="city",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AlterField(
            model_name="nominee",
            name="state",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
