# Generated by Django 6.0.1 on 2026-01-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_investorprofile_foreign_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='ckyc_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='email_declaration',
            field=models.CharField(choices=[('SE', 'Self'), ('SP', 'Spouse'), ('DC', 'Dependent Children'), ('DS', 'Dependent Siblings'), ('DP', 'Dependent Parents'), ('GD', 'Guardian'), ('PM', 'PMS'), ('CD', 'Custodian'), ('PO', 'POA')], default='SE', max_length=2),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='guardian_ckyc_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='guardian_kra_exempt_ref_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='guardian_kyc_type',
            field=models.CharField(blank=True, choices=[('K', 'KRA Compliant'), ('C', 'CKYC Compliant'), ('B', 'Biometric KYC'), ('E', 'Aadhaar E-KYC')], max_length=1),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='kra_exempt_ref_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='kyc_type',
            field=models.CharField(choices=[('K', 'KRA Compliant'), ('C', 'CKYC Compliant'), ('B', 'Biometric KYC'), ('E', 'Aadhaar E-KYC')], default='K', max_length=1),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='mobile_declaration',
            field=models.CharField(choices=[('SE', 'Self'), ('SP', 'Spouse'), ('DC', 'Dependent Children'), ('DS', 'Dependent Siblings'), ('DP', 'Dependent Parents'), ('GD', 'Guardian'), ('PM', 'PMS'), ('CD', 'Custodian'), ('PO', 'POA')], default='SE', max_length=2),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='nomination_auth_mode',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='nomination_opt',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='second_applicant_ckyc_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='second_applicant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='second_applicant_email_declaration',
            field=models.CharField(choices=[('SE', 'Self'), ('SP', 'Spouse'), ('DC', 'Dependent Children'), ('DS', 'Dependent Siblings'), ('DP', 'Dependent Parents'), ('GD', 'Guardian'), ('PM', 'PMS'), ('CD', 'Custodian'), ('PO', 'POA')], default='SE', max_length=2),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='second_applicant_kra_exempt_ref_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='second_applicant_kyc_type',
            field=models.CharField(blank=True, choices=[('K', 'KRA Compliant'), ('C', 'CKYC Compliant'), ('B', 'Biometric KYC'), ('E', 'Aadhaar E-KYC')], max_length=1),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='second_applicant_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='second_applicant_mobile_declaration',
            field=models.CharField(choices=[('SE', 'Self'), ('SP', 'Spouse'), ('DC', 'Dependent Children'), ('DS', 'Dependent Siblings'), ('DP', 'Dependent Parents'), ('GD', 'Guardian'), ('PM', 'PMS'), ('CD', 'Custodian'), ('PO', 'POA')], default='SE', max_length=2),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='third_applicant_ckyc_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='third_applicant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='third_applicant_email_declaration',
            field=models.CharField(choices=[('SE', 'Self'), ('SP', 'Spouse'), ('DC', 'Dependent Children'), ('DS', 'Dependent Siblings'), ('DP', 'Dependent Parents'), ('GD', 'Guardian'), ('PM', 'PMS'), ('CD', 'Custodian'), ('PO', 'POA')], default='SE', max_length=2),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='third_applicant_kra_exempt_ref_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='third_applicant_kyc_type',
            field=models.CharField(blank=True, choices=[('K', 'KRA Compliant'), ('C', 'CKYC Compliant'), ('B', 'Biometric KYC'), ('E', 'Aadhaar E-KYC')], max_length=1),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='third_applicant_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='third_applicant_mobile_declaration',
            field=models.CharField(choices=[('SE', 'Self'), ('SP', 'Spouse'), ('DC', 'Dependent Children'), ('DS', 'Dependent Siblings'), ('DP', 'Dependent Parents'), ('GD', 'Guardian'), ('PM', 'PMS'), ('CD', 'Custodian'), ('PO', 'POA')], default='SE', max_length=2),
        ),
        migrations.AddField(
            model_name='nominee',
            name='id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nominee',
            name='id_type',
            field=models.CharField(blank=True, choices=[('A', 'Passport'), ('B', 'Election ID Card'), ('C', 'PAN Card'), ('D', 'ID Card'), ('E', 'Driving License'), ('G', 'UIDIA / Aadhar letter'), ('H', 'NREGA Job Card'), ('O', 'Others'), ('X', 'Not categorized'), ('T', 'TIN'), ('C1', 'Company Identification Number'), ('G1', 'US GIIN'), ('E1', 'Global Entity Identification Number')], max_length=2),
        ),
    ]
