# Generated by Django 6.0.1 on 2026-01-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_investorprofile_ckyc_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorprofile",
            name="nomination_auth_mode",
            field=models.CharField(
                blank=True, choices=[("O", "Online"), ("P", "Physical")], max_length=1
            ),
        ),
    ]
