# Generated by Django 6.0.1 on 2026-01-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_investorprofile_nomination_auth_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorprofile",
            name="client_type",
            field=models.CharField(
                blank=True,
                choices=[("P", "Physical"), ("D", "Demat")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="email_declaration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SE", "Self"),
                    ("SP", "Spouse"),
                    ("DC", "Dependent Children"),
                    ("DS", "Dependent Siblings"),
                    ("DP", "Dependent Parents"),
                    ("GD", "Guardian"),
                    ("PM", "PMS"),
                    ("CD", "Custodian"),
                    ("PO", "POA"),
                ],
                default="SE",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="kyc_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("K", "KRA Compliant"),
                    ("C", "CKYC Compliant"),
                    ("B", "Biometric KYC"),
                    ("E", "Aadhaar E-KYC"),
                ],
                default="K",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="mobile_declaration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SE", "Self"),
                    ("SP", "Spouse"),
                    ("DC", "Dependent Children"),
                    ("DS", "Dependent Siblings"),
                    ("DP", "Dependent Parents"),
                    ("GD", "Guardian"),
                    ("PM", "PMS"),
                    ("CD", "Custodian"),
                    ("PO", "POA"),
                ],
                default="SE",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="paperless_flag",
            field=models.CharField(
                blank=True,
                choices=[("P", "Physical"), ("Z", "Paperless")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="second_applicant_email_declaration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SE", "Self"),
                    ("SP", "Spouse"),
                    ("DC", "Dependent Children"),
                    ("DS", "Dependent Siblings"),
                    ("DP", "Dependent Parents"),
                    ("GD", "Guardian"),
                    ("PM", "PMS"),
                    ("CD", "Custodian"),
                    ("PO", "POA"),
                ],
                default="SE",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="second_applicant_mobile_declaration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SE", "Self"),
                    ("SP", "Spouse"),
                    ("DC", "Dependent Children"),
                    ("DS", "Dependent Siblings"),
                    ("DP", "Dependent Parents"),
                    ("GD", "Guardian"),
                    ("PM", "PMS"),
                    ("CD", "Custodian"),
                    ("PO", "POA"),
                ],
                default="SE",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="third_applicant_email_declaration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SE", "Self"),
                    ("SP", "Spouse"),
                    ("DC", "Dependent Children"),
                    ("DS", "Dependent Siblings"),
                    ("DP", "Dependent Parents"),
                    ("GD", "Guardian"),
                    ("PM", "PMS"),
                    ("CD", "Custodian"),
                    ("PO", "POA"),
                ],
                default="SE",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="third_applicant_mobile_declaration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SE", "Self"),
                    ("SP", "Spouse"),
                    ("DC", "Dependent Children"),
                    ("DS", "Dependent Siblings"),
                    ("DP", "Dependent Parents"),
                    ("GD", "Guardian"),
                    ("PM", "PMS"),
                    ("CD", "Custodian"),
                    ("PO", "POA"),
                ],
                default="SE",
                max_length=2,
            ),
        ),
    ]
