# Generated by Django 6.0.1 on 2026-01-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_investorprofile_client_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominee",
            name="country",
            field=models.CharField(blank=True, default="India", max_length=35),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="nomination_auth_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("W", "Wet Signature"),
                    ("O", "Online/OTP"),
                    ("E", "eSign"),
                    ("P", "Physical (Legacy)"),
                ],
                max_length=1,
            ),
        ),
    ]
