# Generated by Django 6.0.1 on 2026-01-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_nominee_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorprofile",
            name="nomination_auth_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("W", "Wet Signature"),
                    ("O", "Online/OTP"),
                    ("E", "eSign"),
                    ("P", "Physical (Legacy)"),
                ],
                default="W",
                max_length=1,
            ),
        ),
    ]
