# Generated by Django 6.0.1 on 2026-01-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_investorprofile_nomination_auth_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="bse_remarks",
            field=models.TextField(blank=True, help_text="Response remarks from BSE"),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="nominee_auth_status",
            field=models.CharField(
                choices=[
                    ("A", "Authenticated"),
                    ("P", "Pending"),
                    ("N", "Not Available"),
                ],
                default="N",
                help_text="A: Authenticated, P: Pending, N: Not Available",
                max_length=1,
            ),
        ),
    ]
