# Generated by Django 6.0.1 on 2026-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_investorprofile_bse_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="country_of_birth",
            field=models.CharField(blank=True, default="India", max_length=50),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="exemption_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A - 501(a) Organization"),
                    ("B", "B - US Government"),
                    ("C", "C - State/US Possession"),
                    ("D", "D - Publicly Traded Corp"),
                    ("E", "E - Member of Expanded Affiliated Group"),
                    ("F", "F - Dealer in Securities"),
                    ("G", "G - REIT"),
                    ("H", "H - Regulated Investment Company"),
                    ("I", "I - Common Trust Fund"),
                    ("J", "J - Bank"),
                    ("K", "K - Broker"),
                    ("L", "L - Exempt Trust"),
                    ("M", "M - Tax Exempt Trust 403(b)/457(g)"),
                    ("N", "N - Not Applicable"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="income_slab",
            field=models.CharField(
                choices=[
                    ("31", "Below 1 Lakh"),
                    ("32", "> 1 <= 5 Lacs"),
                    ("33", "> 5 <= 10 Lacs"),
                    ("34", "> 10 <= 25 Lacs"),
                    ("35", "> 25 Lacs <= 1 Crore"),
                    ("36", "Above 1 Crore"),
                ],
                default="32",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="pep_status",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("R", "Relative")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="place_of_birth",
            field=models.CharField(blank=True, default="India", max_length=50),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="source_of_wealth",
            field=models.CharField(
                choices=[
                    ("01", "Salary"),
                    ("02", "Business Income"),
                    ("03", "Gift"),
                    ("04", "Ancestral Property"),
                    ("05", "Rental Income"),
                    ("06", "Prize Money"),
                    ("07", "Royalty"),
                    ("08", "Others"),
                ],
                default="01",
                max_length=2,
            ),
        ),
    ]
