# Generated by Django 6.0.1 on 2026-01-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_investorprofile_country_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("pincode", models.CharField(blank=True, max_length=6)),
            ],
            options={
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="rm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investors",
                to="users.rmprofile",
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investors",
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rms",
                to="users.branch",
            ),
        ),
    ]
