# Generated by Django 6.0.1 on 2026-02-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_branch_investorprofile_rm_investorprofile_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="is_offline",
            field=models.BooleanField(
                default=False,
                help_text="True if investor is onboarded offline via RTA feed and not yet synced with BSE.",
            ),
        ),
    ]
