# Generated by Django 6.0.1 on 2026-02-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_investorprofile_is_offline"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="firstname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="lastname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="middlename",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
