# Generated by Django 6.0.1 on 2026-02-13 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_investorprofile_firstname_investorprofile_lastname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bse_index",
            field=models.IntegerField(
                blank=True,
                help_text="Fixed slot index (1-5) for BSE registration",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankaccount",
            unique_together={("investor", "bse_index")},
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
