# Generated by Django 6.0.1 on 2026-02-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_bankaccount_bse_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorprofile",
            name="account_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("SB", "Savings"),
                    ("CB", "Current"),
                    ("NE", "NRE"),
                    ("NO", "NRO"),
                ],
                default="SB",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="alternate_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="alternate_mobile",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="branch_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="country",
            field=models.CharField(blank=True, default="India", max_length=50),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="dob",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of Birth / Incorporation"
            ),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="gstin",
            field=models.CharField(blank=True, max_length=15, verbose_name="GSTIN"),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this Distributor profile is active.",
            ),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="distributorprofile",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANDAMAN & NICOBAR", "Andaman & Nicobar"),
                    ("ANDHRA PRADESH", "Andhra Pradesh"),
                    ("ARUNACHAL PRADESH", "Arunachal Pradesh"),
                    ("ASSAM", "Assam"),
                    ("BIHAR", "Bihar"),
                    ("CHANDIGARH", "Chandigarh"),
                    ("CHHATTISGARH", "Chhattisgarh"),
                    ("DADRA AND NAGAR HAVELI", "Dadra and Nagar Haveli"),
                    ("DAMAN AND DIU", "Daman and Diu"),
                    ("DELHI", "Delhi"),
                    ("GOA", "Goa"),
                    ("GUJARAT", "Gujarat"),
                    ("HARYANA", "Haryana"),
                    ("HIMACHAL PRADESH", "Himachal Pradesh"),
                    ("JAMMU & KASHMIR", "Jammu & Kashmir"),
                    ("JHARKHAND", "Jharkhand"),
                    ("KARNATAKA", "Karnataka"),
                    ("KERALA", "Kerala"),
                    ("LAKSHADWEEP", "Lakshadweep"),
                    ("MADHYA PRADESH", "Madhya Pradesh"),
                    ("MAHARASHTRA", "Maharashtra"),
                    ("MANIPUR", "Manipur"),
                    ("MEGHALAYA", "Meghalaya"),
                    ("MIZORAM", "Mizoram"),
                    ("NAGALAND", "Nagaland"),
                    ("NEW DELHI", "New Delhi"),
                    ("ODISHA", "Odisha"),
                    ("PUDUCHERRY", "Puducherry"),
                    ("PUNJAB", "Punjab"),
                    ("RAJASTHAN", "Rajasthan"),
                    ("SIKKIM", "Sikkim"),
                    ("TAMIL NADU", "Tamil Nadu"),
                    ("TELANGANA", "Telangana"),
                    ("TRIPURA", "Tripura"),
                    ("UTTAR PRADESH", "Uttar Pradesh"),
                    ("UTTARAKHAND", "Uttarakhand"),
                    ("WEST BENGAL", "West Bengal"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="account_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("SB", "Savings"),
                    ("CB", "Current"),
                    ("NE", "NRE"),
                    ("NO", "NRO"),
                ],
                default="SB",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="alternate_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="alternate_mobile",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="branch_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="country",
            field=models.CharField(blank=True, default="India", max_length=50),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="gstin",
            field=models.CharField(blank=True, max_length=15, verbose_name="GSTIN"),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Designates whether this RM profile is active."
            ),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="rmprofile",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANDAMAN & NICOBAR", "Andaman & Nicobar"),
                    ("ANDHRA PRADESH", "Andhra Pradesh"),
                    ("ARUNACHAL PRADESH", "Arunachal Pradesh"),
                    ("ASSAM", "Assam"),
                    ("BIHAR", "Bihar"),
                    ("CHANDIGARH", "Chandigarh"),
                    ("CHHATTISGARH", "Chhattisgarh"),
                    ("DADRA AND NAGAR HAVELI", "Dadra and Nagar Haveli"),
                    ("DAMAN AND DIU", "Daman and Diu"),
                    ("DELHI", "Delhi"),
                    ("GOA", "Goa"),
                    ("GUJARAT", "Gujarat"),
                    ("HARYANA", "Haryana"),
                    ("HIMACHAL PRADESH", "Himachal Pradesh"),
                    ("JAMMU & KASHMIR", "Jammu & Kashmir"),
                    ("JHARKHAND", "Jharkhand"),
                    ("KARNATAKA", "Karnataka"),
                    ("KERALA", "Kerala"),
                    ("LAKSHADWEEP", "Lakshadweep"),
                    ("MADHYA PRADESH", "Madhya Pradesh"),
                    ("MAHARASHTRA", "Maharashtra"),
                    ("MANIPUR", "Manipur"),
                    ("MEGHALAYA", "Meghalaya"),
                    ("MIZORAM", "Mizoram"),
                    ("NAGALAND", "Nagaland"),
                    ("NEW DELHI", "New Delhi"),
                    ("ODISHA", "Odisha"),
                    ("PUDUCHERRY", "Puducherry"),
                    ("PUNJAB", "Punjab"),
                    ("RAJASTHAN", "Rajasthan"),
                    ("SIKKIM", "Sikkim"),
                    ("TAMIL NADU", "Tamil Nadu"),
                    ("TELANGANA", "Telangana"),
                    ("TRIPURA", "Tripura"),
                    ("UTTAR PRADESH", "Uttar Pradesh"),
                    ("UTTARAKHAND", "Uttarakhand"),
                    ("WEST BENGAL", "West Bengal"),
                ],
                max_length=50,
            ),
        ),
    ]
