# Generated by Django 6.0.1 on 2026-02-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_rmprofile_mobile_onetimepassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rmprofile",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
