# Generated by Django 6.0.1 on 2026-02-15 01:10

from django.db import migrations, models
from django.db.models.functions import Length

def populate_broker_codes(apps, schema_editor):
    DistributorProfile = apps.get_model('users', 'DistributorProfile')
    distributors = DistributorProfile.objects.all().order_by('id')

    count = 1

    # Try to find last code safely
    # Note: historic models might not support complex annotations depending on Django version/backend mocks
    # But usually safe in standard Django migrations.

    qs = DistributorProfile.objects.filter(broker_code__startswith='BBF')
    if qs.exists():
        # Fallback to python sort if needed or trust DB
        codes = list(qs.values_list('broker_code', flat=True))
        # Sort by length desc, then value desc
        codes.sort(key=lambda x: (len(x), x), reverse=True)
        last_code = codes[0]
        try:
             count = int(last_code[3:]) + 1
        except:
             pass

    for dist in distributors:
        if not dist.broker_code:
            dist.broker_code = f"BBF{count:04d}"
            dist.save()
            count += 1

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_rmprofile_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorprofile",
            name="broker_code",
            field=models.CharField(blank=True, default="", help_text="Auto-generated Sub Broker Code (e.g. BBF0001)", max_length=20),
        ),
        migrations.RunPython(populate_broker_codes),
        migrations.AlterField(
            model_name="distributorprofile",
            name="broker_code",
            field=models.CharField(blank=True, default="", help_text="Auto-generated Sub Broker Code (e.g. BBF0001)", max_length=20, unique=True),
        ),
    ]
