# Generated by Django 6.0.1 on 2026-02-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_allow_null_arn_mandatory_broker_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorprofile',
            name='arn_number',
            field=models.CharField(blank=True, help_text='AMFI Registration Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distributorprofile',
            name='broker_code',
            field=models.CharField(blank=True, help_text='Auto-generated Sub Broker Code (e.g. BBF0001)', max_length=20, unique=True),
        ),
    ]
