# Generated by Django 6.0.1 on 2026-02-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_distributorprofile_arn_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorprofile",
            name="old_broker_code",
            field=models.CharField(
                blank=True,
                help_text="Old Broker Code for backward compatibility",
                max_length=20,
                null=True,
            ),
        ),
    ]
