# Generated by Django 6.0.1 on 2026-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_distributorprofile_old_broker_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmprofile",
            name="pan",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
