# Generated by Django 6.0.1 on 2026-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_rmprofile_pan"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_password_change",
            field=models.BooleanField(
                default=False, help_text="Forces user to change password on next login."
            ),
        ),
    ]
