# Generated by Django 6.0.1 on 2026-03-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_user_force_password_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorprofile",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this Distributor is approved to perform actions.",
            ),
        ),
    ]
