# Generated by Django 6.0.1 on 2026-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_distributorprofile_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="micr_code",
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
