# Generated by Django 6.0.1 on 2026-04-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_bankaccount_micr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="ndml_kyc_status",
            field=models.CharField(
                blank=True, help_text="Status code from NDML", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="ndml_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="ndml_reg_ack",
            field=models.CharField(
                blank=True,
                help_text="NDML Registration Acknowledgement",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="ndml_status_desc",
            field=models.TextField(
                blank=True, help_text="Description of the NDML status", null=True
            ),
        ),
        migrations.CreateModel(
            name="NDMLKYCDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(help_text="Raw XML response from NDML download"),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("kyc_mode", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("status_date", models.CharField(blank=True, max_length=50, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ndml_kyc_details",
                        to="users.investorprofile",
                    ),
                ),
            ],
        ),
    ]
