# Generated by Django 6.0.1 on 2026-08-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_investorprofile_ndml_kyc_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='relationship',
            field=models.CharField(choices=[('Aunt', 'Aunt'), ('Brother-in-law', 'Brother-in-law'), ('Brother', 'Brother'), ('Daughter', 'Daughter'), ('Daughter-in-law', 'Daughter-in-law'), ('Father', 'Father'), ('Father-in-law', 'Father-in-law'), ('Grand Daughter', 'Grand Daughter'), ('Grand Father', 'Grand Father'), ('Grand Mother', 'Grand Mother'), ('Grand Son', 'Grand Son'), ('Mother-in-law', 'Mother-in-law'), ('Mother', 'Mother'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Sister', 'Sister'), ('Sister-in-law', 'Sister-in-law'), ('Son', 'Son'), ('Son-in-law', 'Son-in-law'), ('Spouse', 'Spouse'), ('Uncle', 'Uncle'), ('Others', 'Others'), ('Court Appointed Legal Guardian', 'Court Appointed Legal Guardian')], default='Others', max_length=50),
        ),
    ]
