# Generated by Django 6.0.1 on 2026-02-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="My Company", max_length=255),
                ),
                ("company_address", models.TextField(blank=True, null=True)),
                (
                    "company_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_pincode",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "company_country",
                    models.CharField(
                        blank=True, default="India", max_length=100, null=True
                    ),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("company_website", models.URLField(blank=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("gstin", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "arn_code",
                    models.CharField(
                        blank=True,
                        help_text="ARN Code for placing orders",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "default_euin",
                    models.CharField(
                        blank=True,
                        help_text="Default EUIN used if order has none",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "email_host",
                    models.CharField(default="smtp.gmail.com", max_length=255),
                ),
                ("email_port", models.IntegerField(default=587)),
                (
                    "email_host_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_host_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email_use_tls", models.BooleanField(default=True)),
                ("email_use_ssl", models.BooleanField(default=False)),
                (
                    "default_from_email",
                    models.EmailField(default="noreply@example.com", max_length=254),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
    ]
