# Generated by Django 6.0.1 on 2026-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="is_maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="Enable to put the system in maintenance mode and lock out non-admin users.",
            ),
        ),
    ]
