# Generated by Django 6.0.3 on 2026-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_systemconfiguration_is_maintenance_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="report_disclaimer",
            field=models.TextField(
                blank=True,
                default="Disclaimer: All values shown in this report are based on internal calculations and provided for informational purposes only. Please verify with official AMC statements.",
                null=True,
            ),
        ),
    ]
