# Generated by Django 6.0.3 on 2026-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_systemconfiguration_report_disclaimer"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="rta_email_fetch_days",
            field=models.IntegerField(
                default=3, help_text="Number of days to look back for RTA emails"
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="rta_email_host",
            field=models.CharField(
                default="imap.gmail.com",
                help_text="IMAP Host for RTA emails",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="rta_email_password",
            field=models.CharField(
                blank=True,
                help_text="Password or App Password for RTA email",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="rta_email_port",
            field=models.IntegerField(
                default=993, help_text="IMAP Port for RTA emails"
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="rta_email_sender_filters",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of sender emails (e.g., donotreply@camsonline.com)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="rta_email_subject_filters",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of email subjects to filter by",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="rta_email_user",
            field=models.CharField(
                blank=True,
                help_text="Email address for receiving RTA feeds",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="rta_file_passwords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of passwords for RTA ZIP files",
                max_length=500,
                null=True,
            ),
        ),
    ]
