# Generated by Django 6.0.1 on 2026-04-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_systemconfiguration_rta_email_fetch_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfiguration",
            name="ndml_env",
            field=models.CharField(
                choices=[("DEMO", "DEMO"), ("PROD", "PROD")],
                default="DEMO",
                help_text="NDML Environment",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="ndml_mi_id",
            field=models.CharField(
                blank=True, help_text="NDML MI ID", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="ndml_password",
            field=models.CharField(
                blank=True, help_text="NDML API Password", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="ndml_pos_code",
            field=models.CharField(
                blank=True, help_text="NDML POS Code", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="ndml_user_name",
            field=models.CharField(
                blank=True, help_text="NDML API User Name", max_length=100, null=True
            ),
        ),
    ]
