# Generated by Django 6.0.1 on 2026-01-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_scheme_isin_alter_scheme_scheme_code"),
        ("users", "0003_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="RTAFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rta_type",
                    models.CharField(
                        choices=[
                            ("CAMS", "CAMS"),
                            ("KARVY", "Karvy (KFintech)"),
                            ("FRANKLIN", "Franklin Templeton"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="rta_files/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_log", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio_number", models.CharField(max_length=50)),
                (
                    "units",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Weighted Average Cost",
                        max_digits=20,
                    ),
                ),
                (
                    "current_nav",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="users.investorprofile",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="products.scheme",
                    ),
                ),
            ],
            options={
                "ordering": ["investor", "scheme"],
                "unique_together": {("investor", "scheme", "folio_number")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio_number", models.CharField(max_length=50)),
                ("rta_code", models.CharField(help_text="CAMS/Karvy", max_length=20)),
                (
                    "txn_type_code",
                    models.CharField(
                        help_text="Raw transaction type from RTA", max_length=20
                    ),
                ),
                (
                    "txn_number",
                    models.CharField(
                        help_text="Unique Reference No from RTA",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("units", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "nav",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "stt",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "stamp_duty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rta_transactions",
                        to="users.investorprofile",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rta_transactions",
                        to="products.scheme",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="reconciliation.rtafile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["folio_number", "scheme"],
                        name="reconciliat_folio_n_e18cff_idx",
                    ),
                    models.Index(
                        fields=["txn_number"], name="reconciliat_txn_num_d29501_idx"
                    ),
                ],
            },
        ),
    ]
