# Generated by Django 6.0.1 on 2026-02-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_scheme_isin_alter_scheme_scheme_code"),
        ("reconciliation", "0001_initial"),
        ("users", "0016_branch_investorprofile_rm_investorprofile_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holding",
            name="free_units",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="holding",
            name="locked_units",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="ELSS Locked Units",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="pledged_units",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="bse_order_id",
            field=models.CharField(
                blank=True,
                help_text="BSE Order ID for matching",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_provisional",
            field=models.BooleanField(
                default=False,
                help_text="True if sourced from BSE allotment but not yet confirmed by RTA",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("RTA", "RTA Mailback"),
                    ("BSE", "BSE Star MF"),
                    ("MANUAL", "Manual Entry"),
                ],
                default="RTA",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="reconciliation.rtafile",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["bse_order_id"], name="reconciliat_bse_ord_9a59d3_idx"
            ),
        ),
    ]
