# Generated by Django 6.0.1 on 2026-02-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0002_holding_free_units_holding_locked_units_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtafile",
            name="error_file",
            field=models.FileField(
                blank=True, null=True, upload_to="rta_errors/%Y/%m/%d/"
            ),
        ),
    ]
