# Generated by Django 6.0.1 on 2026-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0003_rtafile_error_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tr_flag",
            field=models.CharField(
                blank=True,
                help_text="Transaction Flag from RTA (e.g., P, R)",
                max_length=20,
                null=True,
            ),
        ),
    ]
