# Generated by Django 6.0.1 on 2026-02-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0004_transaction_tr_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="original_txn_number",
            field=models.CharField(
                blank=True,
                help_text="Original RTA Transaction No for display",
                max_length=100,
                null=True,
            ),
        ),
    ]
