# Generated by Django 6.0.1 on 2026-02-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0005_transaction_original_txn_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="tr_flag",
            field=models.CharField(
                blank=True,
                help_text="Transaction Flag from RTA (e.g., P, R)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="txn_type_code",
            field=models.CharField(
                help_text="Raw transaction type from RTA", max_length=100
            ),
        ),
    ]
