# Generated by Django 6.0.1 on 2026-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0006_alter_transaction_tr_flag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bank_account_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="broker_code",
            field=models.CharField(
                blank=True, help_text="ARN Code", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="euin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="instrument_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="instrument_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="load_amount",
            field=models.DecimalField(
                decimal_places=4, default=0, help_text="Exit Load Amount", max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="raw_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Full raw row data from source file"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status_desc",
            field=models.CharField(
                blank=True, help_text="Raw Status from RTA", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sub_broker_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=4, default=0, help_text="TDS/Tax Amount", max_digits=15
            ),
        ),
    ]
