# Generated by Django 6.0.1 on 2026-03-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0008_transaction_ac_no_transaction_amc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_action',
            field=models.CharField(blank=True, help_text='Internal calculated action (e.g. ADD, SUB, DIV_REINV)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(blank=True, help_text='Human-readable transaction type (e.g. Purchase, SIP, Redemption)', max_length=100, null=True),
        ),
    ]
