# Generated by Django 6.0.1 on 2026-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0009_transaction_txn_action_transaction_txn_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="trxn_suffix",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
