# Generated by Django 6.0.1 on 2026-03-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0010_alter_transaction_trxn_suffix"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedRTARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rta_type",
                    models.CharField(
                        choices=[
                            ("CAMS", "CAMS"),
                            ("KARVY", "Karvy (KFintech)"),
                            ("FRANKLIN", "Franklin Templeton"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "original_txn_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "folio_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "row_data",
                    models.JSONField(help_text="Raw row data dictionary that failed"),
                ),
                (
                    "error_reason",
                    models.TextField(
                        help_text="Reason for failure (e.g. 'Scheme not found')"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("FAILED", "Failed"), ("RESOLVED", "Resolved")],
                        default="FAILED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_records",
                        to="reconciliation.rtafile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
