# Generated by Django 6.0.1 on 2026-01-16 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reconciliation', '0001_initial'),
        ('users', '0008_alter_investorprofile_foreign_address_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CASUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cas_uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_uploads', to='users.investorprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_cas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255)),
                ('folio_number', models.CharField(blank=True, max_length=100, null=True)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('amc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('cas_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_holdings', to='analytics.casupload')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_holdings', to='users.investorprofile')),
            ],
            options={
                'ordering': ['investor', 'scheme_name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('target_date', models.DateField()),
                ('category', models.CharField(choices=[('RETIREMENT', 'Retirement'), ('EDUCATION', 'Child Education'), ('HOUSE', 'House Purchase'), ('CAR', 'Car Purchase'), ('VACATION', 'Vacation'), ('EMERGENCY', 'Emergency Fund'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(help_text='The beneficiary of this goal', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.investorprofile')),
                ('user', models.ForeignKey(help_text='The user who created this goal', on_delete=django.db.models.deletion.CASCADE, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of holding allocated to this goal (0-100)', max_digits=5)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='analytics.goal')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_mappings', to='reconciliation.holding')),
            ],
            options={
                'unique_together': {('goal', 'holding')},
            },
        ),
    ]
